# Generated by Django 5.2.10 on 2026-01-31 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_source', models.CharField(choices=[('instagram', 'Instagram'), ('website', 'Web Sitesi'), ('phone', 'Telefon'), ('email', 'E-posta'), ('reference', 'Referans')], max_length=20)),
                ('education_background', models.CharField(choices=[('educated', 'Tekstil Eğitimi Almış'), ('self_taught', 'Alaylı'), ('student', 'Öğrenci'), ('unknown', 'Bilinmiyor')], max_length=20)),
                ('interest_type', models.CharField(choices=[('online', 'Online'), ('onsite', 'Yüz Yüze'), ('both', 'Her İkisi')], max_length=20)),
                ('lead_stage', models.CharField(choices=[('new', 'Yeni Geldi'), ('contacted', 'İlk Görüşme Yapıldı'), ('interested', 'İlgili'), ('follow_up', 'Takip Edilecek'), ('converted', 'Kayıta Döndü'), ('lost', 'Kaybedildi')], default='new', max_length=20)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('first_meeting_date', models.DateTimeField(blank=True, null=True)),
                ('second_meeting_date', models.DateTimeField(blank=True, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_meeting_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_first_meetings', to=settings.AUTH_USER_MODEL)),
                ('interested_trainings', models.ManyToManyField(blank=True, related_name='interested_leads', to='core.training')),
                ('potential_trainings', models.ManyToManyField(blank=True, related_name='potential_leads', to='core.training')),
                ('second_meeting_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_second_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
