# Generated by Django 5.2.10 on 2026-01-31 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='person',
        ),
        migrations.AddField(
            model_name='meeting',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lead'),
        ),
    ]
