# Generated by Django 5.2.10 on 2026-02-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lead_converted_at_lead_converted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_source',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('website', 'Web Sitesi'), ('phone', 'Telefon'), ('whatsapp', 'Whatsapp'), ('email', 'E-posta'), ('reference', 'Referans')], max_length=20),
        ),
    ]
