# Generated by Django 5.2.10 on 2026-02-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lead_district_alter_lead_contact_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='person',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='converted_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='converted_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='converted_person',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='person',
        ),
        migrations.AddField(
            model_name='document',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lead'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='previous_trainings',
            field=models.ManyToManyField(blank=True, related_name='previous_leads', to='core.training'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lead'),
        ),
    ]
