# Generated by Django 5.2.10 on 2026-02-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_document_person_remove_enrollment_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Dekont'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Kayıtlı'), ('completed', 'Tamamladı'), ('dropped', 'Bıraktı')], default='enrolled', max_length=20),
        ),
    ]
